In [42]:
import gc
import os
import pickle
import random
import joblib
import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import average_precision_score as APS
from sklearn.model_selection import ShuffleSplit, StratifiedShuffleSplit
import duckdb
import pandas as pd
import mapply
from sklearn.metrics import average_precision_score, precision_recall_curve
from tokenizers import Tokenizer
from transformers import PreTrainedTokenizerFast
from transformers import AutoConfig, AutoTokenizer, AutoModel, DataCollatorWithPadding
import torch
import torch.nn as nn
import torch.nn.functional as F
import importlib
from torch.optim import Adam, AdamW
import matplotlib.pyplot as plt
import gc
import matplotlib as mpl
import json
from sklearn.metrics import classification_report, cohen_kappa_score
from sklearn.utils import class_weight
from rdkit.Chem import Descriptors
from rdkit.Chem import rdMolDescriptors
from sklearn.preprocessing import StandardScaler
# from keras.layers import Layer
from rdkit import Chem
# from tensorflow.keras.layers import LeakyReLU
class Wrapper:
    def __init__(self, method_name, module_name):
        self.method_name = method_name
        self.module = importlib.import_module(module_name)

    @property
    def method(self):
        return getattr(self.module, self.method_name)

    def __call__(self, *args, **kwargs):
        return self.method(*args, **kwargs)
        
wrapped_mol_from_smiles = Wrapper("MolFromSmiles", "rdkit.Chem")

mapply.init(
    n_workers=10,#was 5 before, trying 10,
    progressbar=True,
)

wrapped_has_substract_match = Wrapper("HasSubstructMatch", "rdkit.Chem")

# calc some descriptors
def calc_descriptors(smile):
    mol = wrapped_mol_from_smiles(smile)
    descr=[round(Descriptors.MolLogP(mol),4),
                  round(Descriptors.TPSA(mol),4),
                  Descriptors.NHOHCount(mol),
                  Descriptors.NOCount(mol),
                  Descriptors.NumHAcceptors(mol),
                  Descriptors.NumHDonors(mol),
                  Descriptors.NumRotatableBonds(mol),
                  Descriptors.NumHeteroatoms(mol),
                  round(Descriptors.FractionCSP3(mol),4),
                  round(Descriptors.ExactMolWt(mol),4),
                  rdMolDescriptors.CalcNumAromaticRings(mol)]
    return np.array(descr,dtype=np.float16)

def get_unique_values(list_of_lists):
    unique_values = []
    for inner_list in list_of_lists:
        for value in inner_list:
            unique_values.append(value)
    return unique_values

In [2]:
all_data = pd.read_csv('all_data_filtered.csv',index_col=[0])

In [3]:
all_data

,Id,smiles,sol_category,sizes
0,EOS12286,Cc1nc(N2CCN(C(=O)Nc3ccc(F)cc3F)CC2)cc(-n2ccnc2)n1,0,49
1,EOS85869,CCN(CC)[C@H]1CCN(C(=O)Cc2nc(C(C)C)c(C)s2)C1,0,43
2,EOS85435,CNC(=O)CNC(=O)c1c(-n2cccc2)sc(C)c1C,0,35
3,EOS102302,CC(C)(C)c1ccc(CSc2cnn(C(C)(C)C)c(=O)c2Cl)cc1,0,44
4,EOS64213,CC[C@H](NC(=O)c1ccnc(-n2ccnc2)c1)c1ccccc1OC,0,43
...,...,...,...,...
70559,EOS37839,O=C(NCCCc1nc(=O)[nH][nH]1)[C@H]1CCC(F)(F)C1,2,43
70560,EOS2088,Cc1ccc(C(=O)NC2CCCC2)cc1S(=O)(=O)N1CCOCC1,2,41
70561,EOS10587,COCCN1CCC(CN(C)S(=O)(=O)c2cccc(C(F)(F)F)c2)C1,2,45
70562,EOS40533,O=C(Nc1ccc(F)cc1)NC1CCN(C(=O)Cc2cnn(-c3ccccc3)...,2,52
70563,EOS45458,COC[C@H](C)NC(=O)N1CCN(c2nnnn2-c2ccccc2)CC1,2,43

In [4]:
print(all_data.sizes.max())
print(all_data.sizes.min())
print(all_data.sizes.mean())

95
18
42.714812085482684

In [36]:
from tokenizers import Tokenizer
from transformers import PreTrainedTokenizerFast
from tokenizers.models import WordLevel,BPE

from tokenizers.pre_tokenizers import Whitespace,Split,ByteLevel

from tokenizers.normalizers import Lowercase, NFKC

enc = { '[PAD]':0,
        'Br':1, 'C':2, 'N':3, 'O':4, 'H':5, 'S':6, 'F':7, 'Cl':8, 'B':9, 'I':10, 
        's':11,'o':12, 'c':13, 'n':14, 'i':15, # is Atomic
        '.':16 ,'=':17 ,'#':18, # bond
        '/':19, # direction
        '-':20, '+': 21, # charge
        '[':22,']':23, # Atomic mass
        '(':24,')':25, # Branches
        '@@':26, '@':27, # tetrahedron
        '1':28,'2':29,'3':30,'4':31,'5':32,'6':33,'7':34,'8':35,'9':36,'Na':37,'P':38,'[UNK]':39
      }



tokenizer = Tokenizer(BPE(vocab=enc, unk_token="[UNK]",merges=[('@','@')]))

tokenizer_fast = PreTrainedTokenizerFast(tokenizer_object=tokenizer)
tokenizer_fast.add_special_tokens({'pad_token': '[PAD]'})
tokenizer_fast.add_special_tokens({'additional_special_tokens':['Br','Cl','Na']})

len(set(enc.values()))

40

In [38]:
def normalize_smile(smile):
    mol = wrapped_mol_from_smiles(smile)
    smiles = Chem.MolToSmiles(mol, canonical=True, isomericSmiles=False)
    return smiles

def encode_smile(smile):
    enc = tokenizer_fast.batch_encode_plus(
        [smile],
        max_length=95,
        padding='max_length',
        return_tensors='np',
        truncation=True
    )['input_ids']
    return enc.astype(np.uint8)

In [7]:


# all_data['smiles'] = all_data['smiles'].apply(normalize_smile)
# all_data['enc_smiles'] = all_data['smiles'].apply(encode_smile)
descr = []
# calc some descriptors
for m in tqdm(all_data.smiles):
    descr.append([Descriptors.MolLogP(Chem.MolFromSmiles(m)),
                  Descriptors.TPSA(Chem.MolFromSmiles(m)),
                  Descriptors.NHOHCount(Chem.MolFromSmiles(m)),
                  Descriptors.NOCount(Chem.MolFromSmiles(m)),
                  Descriptors.NumHAcceptors(Chem.MolFromSmiles(m)),
                  Descriptors.NumHDonors(Chem.MolFromSmiles(m)),
                  Descriptors.NumRotatableBonds(Chem.MolFromSmiles(m)),
                  Descriptors.NumHeteroatoms(Chem.MolFromSmiles(m)),
                  Descriptors.FractionCSP3(Chem.MolFromSmiles(m)),
                  Descriptors.ExactMolWt(Chem.MolFromSmiles(m)),
                  rdMolDescriptors.CalcNumAromaticRings(Chem.MolFromSmiles(m))])

descr = np.asarray(descr)

100%|███████████████████████████████████████████████████████████████████████████| 70564/70564 [02:49<00:00, 416.46it/s]

In [8]:
descr.shape

(70564, 11)

In [9]:
# scaler_descr = StandardScaler()

In [10]:
scaler_descr = torch.load('rdkit_descriptor_scaler_sol')
descr_scaled = scaler_descr.transform(descr)

In [11]:
# torch.save(scaler_descr,'rdkit_descriptor_scaler_sol')

In [11]:
all_data['norm_smiles'] = all_data['smiles'].apply(normalize_smile)
all_data['enc_smiles'] = all_data['norm_smiles'].apply(encode_smile)

In [12]:
unk_counter = 0
for item in range(len(all_data['enc_smiles'].values)):
    if 39 in all_data['enc_smiles'].values[item]:
        unk_counter+=1
print(unk_counter)

5

In [13]:
# V6bs
import torch.nn.functional as F
from torch.nn import Linear, Conv1d, Embedding, AdaptiveMaxPool1d, AdaptiveAvgPool1d
from torch_geometric.nn import BatchNorm


class CNN1D(torch.nn.Module):
    def __init__(self,
                 conv_filters = 64,
                 conv_layers = 5,
                 emb_dim = 256,
                 kernel_size = 5,
                 linear_neurons=1024):

        super(CNN1D, self).__init__()
        
        self.emb_dim = emb_dim
        
        self.conv_filters = conv_filters

        self.num_conv1d_layers = conv_layers
        
        self.smile_emb = Embedding(num_embeddings=40, embedding_dim=emb_dim)

        self.conv1d_layers = nn.ModuleList()

        for i in range(conv_layers):
            if i == 0:
                self.conv1d_layers.append(
                    Conv1d(in_channels=emb_dim, out_channels=conv_filters * (i+1), kernel_size=kernel_size, stride=1))
            else:
                self.conv1d_layers.append(
                Conv1d(in_channels=conv_filters * i, out_channels=conv_filters * (i+1), kernel_size=kernel_size, stride=1))

        self.maxpool = AdaptiveMaxPool1d(1)
        self.avgpool = AdaptiveAvgPool1d(1)


        self.conv_act = nn.ReLU()
        self.batchnorm = nn.BatchNorm1d(11 + (conv_filters * (conv_layers) * 2))

        # self.actfc = nn.LeakyReLU(negative_slope=0.1)

        # self.gated_mlp = Gated_MLP_block(384)

        self.out_mlp = nn.Sequential(Linear(in_features= 11 + (conv_filters * (conv_layers) * 2), out_features=linear_neurons),
                                     nn.BatchNorm1d(linear_neurons),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                    Linear(in_features=linear_neurons, out_features=linear_neurons //2),
                                     nn.BatchNorm1d(linear_neurons // 2),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                     Linear(in_features=linear_neurons // 2, out_features=linear_neurons //4),
                                     nn.BatchNorm1d(linear_neurons // 4),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                     Linear(in_features=linear_neurons // 4, out_features=linear_neurons // 8),
                                     nn.BatchNorm1d(linear_neurons // 8),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                     )

        self.layer_out = Linear(in_features=linear_neurons // 8, out_features=3)

    def forward(self, smile_vec,rdkit):

        smile_emb = self.smile_emb(smile_vec)

        conv_out = smile_emb.reshape(len(smile_emb), self.emb_dim, -1)

        for i in range(self.num_conv1d_layers):
            conv_out = self.conv1d_layers[i](conv_out)
            conv_out = self.conv_act(conv_out)

        conv_out_max = self.maxpool(conv_out).reshape(len(conv_out), self.conv_filters * self.num_conv1d_layers)
        conv_out_avg = self.avgpool(conv_out).reshape(len(conv_out), self.conv_filters * self.num_conv1d_layers)

        out = torch.cat((conv_out_max,conv_out_avg,rdkit), dim=1)
        out = self.batchnorm(out)

        out = self.out_mlp(out)

        out = self.layer_out(out)

        return out

In [14]:
def get_loader(smile_emb,rdkit_f,y=None, with_y=True, shuffle=False, batch_size=4096):
    if with_y:
        train = torch.utils.data.TensorDataset(torch.from_numpy(smile_emb).long(),
                                               torch.from_numpy(rdkit_f).float(),
                                           torch.from_numpy(y.flatten()).long())
    if not with_y:
        train = torch.utils.data.TensorDataset(torch.from_numpy(smile_emb).long(),
                                              torch.from_numpy(rdkit_f).float())
        
    train_loader = torch.utils.data.DataLoader(train, 
                                               batch_size=batch_size,shuffle=shuffle)
    return train_loader

In [14]:
def train_epoch(model, optimizer, train_loader, criterion, device):
    model.train()
    for smile_emb,rdkit_f,y in train_loader:
  
        out = model(smile_emb.to(device),rdkit_f.to(device))
        loss = criterion(out, y.to(device))

        # backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

def evaluate_loss(loader, model, criterion, device, metric=None):
    model.eval()
    with torch.no_grad():
        loss = 0
        j = 0
        sg = nn.Softmax()
        for smile_emb,rdkit_f,y in loader:
            out = model(smile_emb.to(device),rdkit_f.to(device))
            loss += criterion(out, y.to(device))
            if metric is not None:
                metric.update(sg(out), y.to(device).long())
            j += 1
        return (loss / j)


def train_m_v3(model, opt, train_loader, val_loader, criterion, n_epochs, device, name, 
               metric=None, early_stop=5,scheduler=None, verbose=True):
    train_log = []
    val_log = []
    val_metric_log = []
    train_metric_log = []
    val_min = np.inf
    train_min = np.inf
    epoch_min = 0
    fixed_epoch_val = 0
    fixed_epoch_train = 0
    val_allowed_maximum = np.inf
    early_counter = 0

    for epoch in tqdm(range(n_epochs)):
        train_epoch(model, opt, train_loader, criterion, device)
        train_loss = evaluate_loss(train_loader, model, criterion, device, metric)
        
        if metric is not None:
            train_metric = metric.compute().cpu().numpy().item()
            metric.reset()
        elif metric is None:
            train_metric = torch.tensor([0])

        val_loss = evaluate_loss(val_loader, model,
                                 criterion, device, metric)
        if metric is not None:
            val_metric = metric.compute().cpu().numpy().item()
            metric.reset()

        elif metric is None:
            train_metric = torch.tensor([0])
        
        if scheduler is not None:
            scheduler.step(val_loss)
            
        train_log.append(train_loss.cpu().numpy().item())
        val_log.append(val_loss.cpu().numpy().item())

        train_metric_log.append(train_metric)
        val_metric_log.append(val_metric)
        
        if val_loss < val_min:
            val_min = val_loss.cpu().numpy().item()
            epoch_val_absolute_min = epoch
            val_allowed_maximum = val_loss * 1.0001 #removed allowance for validation fluctuation

        if train_loss < train_min:
            train_min = train_loss

        if val_loss <= val_allowed_maximum:
            epoch_min = epoch
            fixed_epoch_val = val_loss.cpu().numpy().item()
            fixed_epoch_train = train_min.cpu().numpy().item()
            torch.save(model.state_dict(), name)
            torch.save({
                'epoch': epoch_min,
                'optimizer_state_dict': optimizer.state_dict(),
                'train_loss_history': train_log,
                'val_loss_history': val_log,
                'train_metric_history': train_metric_log,
                'val_metric_history': val_metric_log,
            }, name + 'training_optimizer_logs_')
            early_counter = 0

        if val_loss > val_allowed_maximum:
            early_counter += 1

        if verbose:
            # if epoch % 1 == 0:
            print(f'Epoch [{epoch + 1}/{n_epochs}], Loss (train/test): {train_loss}/{val_loss},'  
            f'AP (train/test): {train_metric_log[-1]}/{val_metric_log[-1]}')

        res_dict = {'min_loss_epoch': epoch_min,
                    'train_min': train_min.cpu().numpy().item(),
                    'train_loss_history': train_log,
                    'val_loss_history': val_log,
                    'val_min': val_min,
                    'final_val': fixed_epoch_val,
                    'final_train': fixed_epoch_train,
                'train_metric_history': train_metric_log,
                'val_metric_history': val_metric_log}

        if early_counter == early_stop:
            print(
                f'Early stopping after epoch {epoch}, model saved at epoch {epoch_min}, validation loss {fixed_epoch_val}.')
            return res_dict

    return res_dict

In [15]:
indep_idx = []
with open(f'solubility_indep_ids.txt', 'r') as fp:
    for line in fp.read().splitlines():
        indep_idx.append(line)
ind_id = all_data[all_data.Id.isin(indep_idx)].index

In [26]:
# train_idx = []
# with open(f'solubility_train_id_{0}.txt', 'r') as fp:
#     for line in fp.read().splitlines():
#         train_idx.append(line)

In [28]:
# tmp = all_data[all_data.Id.isin(indep_idx)]

In [29]:
# tmp

,Id,smiles,sol_category,sizes,norm_smiles,enc_smiles
17,EOS23248,CCOc1ccc(NC(=O)c2ccc(-n3cnnn3)cc2)cc1,0,37,CCOc1ccc(NC(=O)c2ccc(-n3cnnn3)cc2)cc1,"[[2, 2, 4, 13, 28, 13, 13, 13, 24, 3, 2, 24, 1..."
20,EOS86630,COCCn1cc(NC(=O)N2CCN(Cc3cc(C)no3)CC2)cn1,0,40,COCCn1cc(NC(=O)N2CCN(Cc3cc(C)no3)CC2)cn1,"[[2, 4, 2, 2, 14, 28, 13, 13, 24, 3, 2, 24, 17..."
23,EOS317,O=C(c1cccc(N2CCCCS2(=O)=O)c1)N1CCc2ccccc21,0,42,O=C(c1cccc(N2CCCCS2(=O)=O)c1)N1CCc2ccccc21,"[[4, 17, 2, 24, 13, 28, 13, 13, 13, 13, 24, 3,..."
29,EOS49570,Cc1ccccc1[C@@H](NS(=O)(=O)C1CCS(=O)(=O)CC1)C1CC1,0,48,Cc1ccccc1C(NS(=O)(=O)C1CCS(=O)(=O)CC1)C1CC1,"[[2, 13, 28, 13, 13, 13, 13, 13, 28, 2, 24, 3,..."
50,EOS20280,CC(C)C[C@H]1C(=O)N2C[C@@H](N(C)C)C[C@H]2CN1C(=...,0,68,CC(C)CC1C(=O)N2CC(N(C)C)CC2CN1C(=O)CCc1nc(-c2c...,"[[2, 2, 24, 2, 25, 2, 2, 28, 2, 24, 17, 4, 25,..."
...,...,...,...,...,...,...
70537,EOS69640,C#CC(CC)(CC)NC(=O)C1CCN(S(=O)(=O)c2ccc(OC)cc2)CC1,2,49,C#CC(CC)(CC)NC(=O)C1CCN(S(=O)(=O)c2ccc(OC)cc2)CC1,"[[2, 18, 2, 2, 24, 2, 2, 25, 24, 2, 2, 25, 3, ..."
70542,EOS81766,Cc1ccc(CC(=O)N[C@H]2CCc3nc(C)cn3C2)cn1,2,38,Cc1ccc(CC(=O)NC2CCc3nc(C)cn3C2)cn1,"[[2, 13, 28, 13, 13, 13, 24, 2, 2, 24, 17, 4, ..."
70557,EOS39302,CCN(Cc1ccc(Cl)s1)C(=O)CCc1c(C)[nH]c(C)nc1=O,2,43,CCN(Cc1ccc(Cl)s1)C(=O)CCc1c(C)[nH]c(C)nc1=O,"[[2, 2, 3, 24, 2, 13, 28, 13, 13, 13, 24, 8, 2..."
70561,EOS10587,COCCN1CCC(CN(C)S(=O)(=O)c2cccc(C(F)(F)F)c2)C1,2,45,COCCN1CCC(CN(C)S(=O)(=O)c2cccc(C(F)(F)F)c2)C1,"[[2, 4, 2, 2, 3, 28, 2, 2, 2, 24, 2, 3, 24, 2,..."
70562,EOS40533,O=C(Nc1ccc(F)cc1)NC1CCN(C(=O)Cc2cnn(-c3ccccc3)...,2,52,O=C(Nc1ccc(F)cc1)NC1CCN(C(=O)Cc2cnn(-c3ccccc3)...,"[[4, 17, 2, 24, 3, 13, 28, 13, 13, 13, 24, 7, ..."

In [30]:
# tmp[tmp.Id.isin(train_idx)]

Empty DataFrame
Columns: [Id, smiles, sol_category, sizes, norm_smiles, enc_smiles]
Index: []

In [16]:
TARGET = ['sol_category']
BATCH_SIZE = int(2048)
ind_id = all_data[all_data.Id.isin(indep_idx)].index
indep_loader = get_loader(np.concatenate(all_data['enc_smiles'].loc[ind_id].to_numpy()).reshape(len(all_data['enc_smiles'].loc[ind_id]),-1),
                          descr_scaled[ind_id],
                          y=all_data[TARGET].loc[ind_id, TARGET].to_numpy(), 
                          with_y=True, 
                          shuffle=False, 
                          batch_size=BATCH_SIZE)

In [17]:
def kappa_val_func(x,y_train_answers,pred_train_probas):
    x1,x2,x3 = x
    local_preds = pred_train_probas**np.array([x1,x2,x3])
    return -round(cohen_kappa_score(y_train_answers, local_preds.argmax(axis=1),weights='quadratic'),4)

In [39]:
from torcheval.metrics import MulticlassAUPRC
from scipy.optimize import minimize
bounds = [(0.01,4)]*3
x0 = [1.0]*3
##V2 - balance the weights
##V3 - lr 1e-4, weight decay
##V4 - lr 1e-4, weight decay, 10 early, smaller neural
##V4A - lr 1e-3, no weight decay, 10 early, smaller neural, no balance, bigger batch 2048, lr 1e-3 
##V5 - same as V6, no rdkit
##V6 - with rdkit
##V6S - use shuffle split instead of kfold
##V7S - with extra features from winning notebooks, except compound id
##V6B - 5 randomizations, no features from winning notebook, new val and train
##V6B_s - 5 randomizations, no features from winning notebook, new val and train, smaller emb 256
##V6B_f - 5 randomizations, no features from winning notebook, new val and train, 512, proper val and ind
TARGET = ['sol_category']
MODEL_VERSION = 'V6B_s2'
EARLY_STOP = 10
BATCH_SIZE = int(2048)
LR = 1e-4
WD = 0.00
EPOCHS = 60
NFOLDS = 3
WH_BALANCE = ''
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

indep_loader = get_loader(np.concatenate(all_data['enc_smiles'].loc[ind_id].to_numpy()).reshape(len(all_data['enc_smiles'].loc[ind_id]),-1),
                          descr_scaled[ind_id],
                          y=all_data[TARGET].loc[ind_id, TARGET].to_numpy(), 
                          with_y=True, 
                          shuffle=False, 
                          batch_size=BATCH_SIZE)

for fold in range(5):
    val_ID = []
    with open(f'solubility_valid_id_{fold}.txt', 'r') as fp:
        for line in fp.read().splitlines():
            val_ID.append(line)

    train_ID = []
    with open(f'solubility_train_id_{fold}.txt', 'r') as fp:
        for line in fp.read().splitlines():
            train_ID.append(line)

    train_idx = all_data[all_data.Id.isin(train_ID)].index
    val_idx = all_data[all_data.Id.isin(val_ID)].index
    
    train_loader = get_loader(np.concatenate(all_data['enc_smiles'].loc[train_idx].to_numpy()).reshape(len(all_data['enc_smiles'].loc[train_idx]),-1),
                              descr_scaled[train_idx],
                              y=all_data[TARGET].loc[train_idx, TARGET].to_numpy(), 
                              with_y=True, 
                              shuffle=True, 
                              batch_size=BATCH_SIZE)
    val_loader = get_loader(np.concatenate(all_data['enc_smiles'].loc[val_idx].to_numpy()).reshape(len(all_data['enc_smiles'].loc[val_idx]),-1),
                            descr_scaled[val_idx],
                            y=all_data[TARGET].loc[val_idx, TARGET].to_numpy(), 
                            with_y=True, 
                            shuffle=False, 
                            batch_size=BATCH_SIZE)
    
    curr_name = f"1DCNN_SOL_{fold}_{MODEL_VERSION}_{WH_BALANCE}"
    
    
    neural = CNN1D()

    
    # neural = nn.DataParallel(neural)
    neural = neural.to(device)

    metric = MulticlassAUPRC(num_classes=3)
    metric.to(device)
    # optimizer = AdamW(neural.parameters(), lr=LR, weight_decay=WD)
    optimizer = Adam(neural.parameters(), lr=LR)
    # scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, 'min', factor=0.1, patience=5)
    class_weights=class_weight.compute_class_weight(class_weight='balanced',classes=np.unique(all_data[TARGET].loc[train_idx, TARGET].to_numpy()),y=all_data[TARGET].loc[train_idx, TARGET].to_numpy().flatten())
    class_weights=torch.tensor(class_weights,dtype=torch.float).to(device)
    if WH_BALANCE == 'balanced':
        loss = nn.CrossEntropyLoss(weight=class_weights)
    else:
        loss = nn.CrossEntropyLoss()

    neural_folder = '1dCNN_pytorch_neurals_upd/'

    os.makedirs(neural_folder,exist_ok=True)
    
    res_dict = train_m_v3(neural, optimizer, train_loader, val_loader, loss, EPOCHS, 
                          device, neural_folder+curr_name,metric,early_stop=EARLY_STOP, verbose=True) 
        
    with torch.cuda.device(device):
        torch.cuda.empty_cache()
    
    mpl.rcParams['figure.dpi'] = 150
    print(res_dict['min_loss_epoch'], res_dict['final_val'], res_dict['final_train'], res_dict['val_min'])
    
    with open(os.path.join(neural_folder, curr_name+'_results.txt'), "w") as f:
        f.write(json.dumps(res_dict))

    y1 = []
    y2 = []
    for lg in res_dict['train_loss_history']:
        y1.append(lg)
    for lg in res_dict['val_loss_history']:
        y2.append(lg)
    x = range(1,len(y1)+1)
    plt.plot(x,y1, label = 'train loss')
    plt.plot(x,y2, label = 'val loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.savefig(neural_folder+curr_name+'_loss_func.png')
    plt.clf()
    plt.close()
    
    sol_types = ['LOW','MEDIUM','HIGH']
    
    ##find coefs
    neural = CNN1D()
    neural.load_state_dict(torch.load(neural_folder+curr_name,map_location=device))
    neural = neural.to(device)
    neural.eval()
    
    y_answers = []
    pred_probas = []
    with torch.no_grad():
        m = nn.Softmax(dim=1)
        for smile_emb,rdkit_f,y in train_loader:
            out = neural(smile_emb.to(device),rdkit_f.to(device))
            pred = m(out.to(torch.device("cpu"))).detach().numpy()
            y_answers.extend(y.to(torch.device("cpu")).detach().numpy())
            pred_probas.extend(pred)
    y_answers = np.array(y_answers)
    pred_probas = np.array(pred_probas)

    minim_res = minimize(kappa_val_func, x0,args=(y_answers,pred_probas), method='powell',bounds=bounds)
    coefs = np.array(minim_res.x)

    with open(f'kappa_coefs_{curr_name}.txt', 'w') as fp:
        for item in coefs:
            # write each item on a new line
            fp.write("%s\n" % item)
        
    ##val
    y_answers = []
    pred_probas = []
    with torch.no_grad():
        m = nn.Softmax(dim=1)
        for smile_emb,rdkit_f,y in val_loader:
            out = neural(smile_emb.to(device),rdkit_f.to(device))
            pred = m(out.to(torch.device("cpu"))).detach().numpy()
            y_answers.extend(y.to(torch.device("cpu")).detach().numpy())
            pred_probas.extend(pred)
    y_answers = np.array(y_answers)
    pred_probas = np.array(pred_probas)
    
    precs = []
    recs = []
    aps = []
    
    for cl in range(0, 3):
        precision, recall, _ = precision_recall_curve((y_answers==cl).astype(int), pred_probas[:, cl], pos_label=1)
        average_precision = average_precision_score((y_answers==cl).astype(int), pred_probas[:, cl], pos_label=1)
        precs.append(precision)
        recs.append(recall)
        aps.append(average_precision)
    
    print(classification_report(y_answers, pred_probas.argmax(axis=1), target_names=sol_types),
          file=open(neural_folder+'valdiation_classification_report'+curr_name+'.txt', 'a'))

    print(classification_report(y_answers, (pred_probas**coefs).argmax(axis=1), target_names=sol_types),
          file=open(neural_folder+'coef_valdiation_classification_report'+curr_name+'.txt', 'a'))
    
    
    mpl.rcParams['figure.dpi'] = 150
    kappa = round(cohen_kappa_score(y_answers, pred_probas.argmax(axis=1),weights='quadratic'),4)
    adj_kappa = round(cohen_kappa_score(y_answers, (pred_probas**coefs).argmax(axis=1),weights='quadratic'),4)
    plt.title(f'Precision-recall curve, Quadratic kappa {kappa}, adjusted {adj_kappa}', fontsize=14)
    
    for marker in range(3):
        plt.plot(recs[marker], precs[marker], label=f'AUC {sol_types[marker]} = %0.2f' % aps[marker])
    plt.legend(loc='lower right')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.xticks(np.arange(0, 1.1, 0.1), fontsize=9)
    plt.yticks(np.arange(0, 1.1, 0.1), fontsize=9)
    plt.grid(True)
    plt.savefig(neural_folder+f'valdiation_precision_recall_{curr_name}.png', format="png")
    plt.close()

    ##indep
    y_answers = []
    pred_probas = []
    with torch.no_grad():
        m = nn.Softmax(dim=1)
        for smile_emb,rdkit_f,y in indep_loader:
            out = neural(smile_emb.to(device),rdkit_f.to(device))
            pred = m(out.to(torch.device("cpu"))).detach().numpy()
            y_answers.extend(y.to(torch.device("cpu")).detach().numpy())
            pred_probas.extend(pred)
    y_answers = np.array(y_answers)
    pred_probas = np.array(pred_probas)
    precs = []
    recs = []
    aps = []
    
    for cl in range(0, 3):
        precision, recall, _ = precision_recall_curve((y_answers==cl).astype(int), pred_probas[:, cl], pos_label=1)
        average_precision = average_precision_score((y_answers==cl).astype(int), pred_probas[:, cl], pos_label=1)
        precs.append(precision)
        recs.append(recall)
        aps.append(average_precision)
    
    print(classification_report(y_answers, pred_probas.argmax(axis=1), target_names=sol_types),
          file=open(neural_folder+'indep_classification_report'+curr_name+'.txt', 'a'))
    print(classification_report(y_answers, (pred_probas**coefs).argmax(axis=1), target_names=sol_types),
          file=open(neural_folder+'coef_indep_classification_report'+curr_name+'.txt', 'a'))
    
    
    mpl.rcParams['figure.dpi'] = 150
    kappa = round(cohen_kappa_score(y_answers, pred_probas.argmax(axis=1),weights='quadratic'),4)
    adj_kappa = round(cohen_kappa_score(y_answers, (pred_probas**coefs).argmax(axis=1),weights='quadratic'),4)
    plt.title(f'Precision-recall curve, Quadratic kappa {kappa}, adjusted {adj_kappa}', fontsize=14)
    
    for marker in range(3):
        plt.plot(recs[marker], precs[marker], label=f'AUC {sol_types[marker]} = %0.2f' % aps[marker])
    plt.legend(loc='lower right')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.xticks(np.arange(0, 1.1, 0.1), fontsize=9)
    plt.yticks(np.arange(0, 1.1, 0.1), fontsize=9)
    plt.grid(True)
    plt.savefig(neural_folder+f'indep_precision_recall_{curr_name}.png', format="png")
    plt.close()

  0%|                                                                                           | 0/60 [00:00<?, ?it/s]C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
  2%|█▍                                                                                 | 1/60 [00:02<02:48,  2.86s/it]

Epoch [1/60], Loss (train/test): 1.1056157350540161/1.1057534217834473,AP (train/test): 0.3408709466457367/0.3413509130477905

  3%|██▊                                                                                | 2/60 [00:05<02:43,  2.82s/it]

Epoch [2/60], Loss (train/test): 0.9305105805397034/0.9256922006607056,AP (train/test): 0.34381532669067383/0.3445216417312622

  5%|████▏                                                                              | 3/60 [00:08<02:41,  2.83s/it]

Epoch [3/60], Loss (train/test): 0.8347632884979248/0.8293845653533936,AP (train/test): 0.34786126017570496/0.3395651578903198

  7%|█████▌                                                                             | 4/60 [00:11<02:37,  2.82s/it]

Epoch [4/60], Loss (train/test): 0.7211135625839233/0.7136250138282776,AP (train/test): 0.3576723039150238/0.3380739390850067

  8%|██████▉                                                                            | 5/60 [00:14<02:33,  2.79s/it]

Epoch [5/60], Loss (train/test): 0.6322205066680908/0.6211863160133362,AP (train/test): 0.3566363751888275/0.33840829133987427

 10%|████████▎                                                                          | 6/60 [00:16<02:30,  2.79s/it]

Epoch [6/60], Loss (train/test): 0.5929661989212036/0.5806236267089844,AP (train/test): 0.35728394985198975/0.3375060260295868

 12%|█████████▋                                                                         | 7/60 [00:19<02:28,  2.79s/it]

Epoch [7/60], Loss (train/test): 0.5387367010116577/0.5222532153129578,AP (train/test): 0.35977280139923096/0.3400798738002777

 13%|███████████                                                                        | 8/60 [00:22<02:25,  2.79s/it]

Epoch [8/60], Loss (train/test): 0.47851336002349854/0.4618615210056305,AP (train/test): 0.366000235080719/0.3410564661026001

 15%|████████████▍                                                                      | 9/60 [00:25<02:23,  2.81s/it]

Epoch [9/60], Loss (train/test): 0.44574740529060364/0.4269866645336151,AP (train/test): 0.37007659673690796/0.345294713973999

 17%|█████████████▋                                                                    | 10/60 [00:28<02:21,  2.83s/it]

Epoch [10/60], Loss (train/test): 0.4332268238067627/0.4157705008983612,AP (train/test): 0.37245476245880127/0.34188175201416016

 18%|███████████████                                                                   | 11/60 [00:30<02:16,  2.79s/it]

Epoch [11/60], Loss (train/test): 0.3812456429004669/0.36371684074401855,AP (train/test): 0.3822457790374756/0.3418351411819458

 20%|████████████████▍                                                                 | 12/60 [00:33<02:14,  2.80s/it]

Epoch [12/60], Loss (train/test): 0.36655500531196594/0.34861627221107483,AP (train/test): 0.3876168727874756/0.3408798575401306

 22%|█████████████████▊                                                                | 13/60 [00:36<02:11,  2.80s/it]

Epoch [13/60], Loss (train/test): 0.3649218678474426/0.35091081261634827,AP (train/test): 0.3928716778755188/0.34317857027053833

 23%|███████████████████▏                                                              | 14/60 [00:39<02:08,  2.80s/it]

Epoch [14/60], Loss (train/test): 0.3499089181423187/0.3409336805343628,AP (train/test): 0.408423513174057/0.34138166904449463

 25%|████████████████████▌                                                             | 15/60 [00:42<02:06,  2.81s/it]

Epoch [15/60], Loss (train/test): 0.3166888952255249/0.3099265992641449,AP (train/test): 0.42027682065963745/0.3418821096420288

 27%|█████████████████████▊                                                            | 16/60 [00:44<02:03,  2.80s/it]

Epoch [16/60], Loss (train/test): 0.2962147891521454/0.2948073744773865,AP (train/test): 0.43354377150535583/0.33993154764175415

 28%|███████████████████████▏                                                          | 17/60 [00:47<01:58,  2.75s/it]

Epoch [17/60], Loss (train/test): 0.270168274641037/0.2816002070903778,AP (train/test): 0.4592093825340271/0.3397231698036194

 30%|████████████████████████▌                                                         | 18/60 [00:50<01:56,  2.77s/it]

Epoch [18/60], Loss (train/test): 0.2488568127155304/0.279043048620224,AP (train/test): 0.5211660861968994/0.3414763808250427

 32%|█████████████████████████▉                                                        | 19/60 [00:53<01:53,  2.76s/it]

Epoch [19/60], Loss (train/test): 0.2998466193675995/0.34818077087402344,AP (train/test): 0.5683827996253967/0.3396400213241577

 33%|███████████████████████████▎                                                      | 20/60 [00:55<01:52,  2.80s/it]

Epoch [20/60], Loss (train/test): 0.19998516142368317/0.2705768942832947,AP (train/test): 0.6253644824028015/0.3369555175304413

 35%|████████████████████████████▋                                                     | 21/60 [00:58<01:48,  2.79s/it]

Epoch [21/60], Loss (train/test): 0.21003076434135437/0.30104389786720276,AP (train/test): 0.667698085308075/0.34105628728866577

 37%|██████████████████████████████                                                    | 22/60 [01:01<01:46,  2.79s/it]

Epoch [22/60], Loss (train/test): 0.1643478274345398/0.2699417471885681,AP (train/test): 0.6947377920150757/0.3409698009490967

 38%|███████████████████████████████▍                                                  | 23/60 [01:04<01:42,  2.78s/it]

Epoch [23/60], Loss (train/test): 0.2048521786928177/0.3350549340248108,AP (train/test): 0.7591347098350525/0.33830174803733826

 40%|████████████████████████████████▊                                                 | 24/60 [01:06<01:38,  2.73s/it]

Epoch [24/60], Loss (train/test): 0.12280949205160141/0.2728736102581024,AP (train/test): 0.7715100049972534/0.3363038897514343

 42%|██████████████████████████████████▏                                               | 25/60 [01:09<01:35,  2.73s/it]

Epoch [25/60], Loss (train/test): 0.1511802226305008/0.32409030199050903,AP (train/test): 0.8319991827011108/0.3383699059486389

 43%|███████████████████████████████████▌                                              | 26/60 [01:12<01:33,  2.74s/it]

Epoch [26/60], Loss (train/test): 0.09712743014097214/0.2775922417640686,AP (train/test): 0.8364546298980713/0.33662253618240356

 45%|████████████████████████████████████▉                                             | 27/60 [01:15<01:30,  2.74s/it]

Epoch [27/60], Loss (train/test): 0.10257872194051743/0.3095061182975769,AP (train/test): 0.8905052542686462/0.33729302883148193

 47%|██████████████████████████████████████▎                                           | 28/60 [01:17<01:27,  2.75s/it]

Epoch [28/60], Loss (train/test): 0.08103011548519135/0.291781485080719,AP (train/test): 0.9020645022392273/0.33751142024993896

 48%|███████████████████████████████████████▋                                          | 29/60 [01:20<01:25,  2.75s/it]

Epoch [29/60], Loss (train/test): 0.07752282917499542/0.2995189130306244,AP (train/test): 0.9283916354179382/0.33663374185562134

 50%|█████████████████████████████████████████                                         | 30/60 [01:23<01:22,  2.75s/it]

Epoch [30/60], Loss (train/test): 0.08447310328483582/0.35350340604782104,AP (train/test): 0.9379665851593018/0.34068533778190613

 52%|██████████████████████████████████████████▎                                       | 31/60 [01:26<01:19,  2.75s/it]

Epoch [31/60], Loss (train/test): 0.0633457750082016/0.32374611496925354,AP (train/test): 0.9642733931541443/0.33892619609832764

 52%|██████████████████████████████████████████▎                                       | 31/60 [01:28<01:23,  2.87s/it]

Epoch [32/60], Loss (train/test): 0.05242210254073143/0.3102950155735016,AP (train/test): 0.981956958770752/0.3383886516094208
Early stopping after epoch 31, model saved at epoch 21, validation loss 0.2699417471885681.
21 0.2699417471885681 0.1643478274345398 0.2699417471885681

C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
  0%|                                                                                           | 0/60 [00:00<?, ?it/s]C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
  2%|█▍                                                                                 | 1/60 [00:02<02:50,  2.89s/it]

Epoch [1/60], Loss (train/test): 1.0404993295669556/1.0384492874145508,AP (train/test): 0.34437939524650574/0.3401913642883301

  3%|██▊                                                                                | 2/60 [00:05<02:40,  2.77s/it]

Epoch [2/60], Loss (train/test): 0.9233279824256897/0.918178141117096,AP (train/test): 0.34542927145957947/0.33820468187332153

  5%|████▏                                                                              | 3/60 [00:08<02:38,  2.78s/it]

Epoch [3/60], Loss (train/test): 0.8595360517501831/0.8525397777557373,AP (train/test): 0.34886860847473145/0.33620572090148926

  7%|█████▌                                                                             | 4/60 [00:11<02:36,  2.80s/it]

Epoch [4/60], Loss (train/test): 0.7791737914085388/0.7748727202415466,AP (train/test): 0.35928791761398315/0.33794185519218445

  8%|██████▉                                                                            | 5/60 [00:14<02:34,  2.81s/it]

Epoch [5/60], Loss (train/test): 0.6781330704689026/0.6750661134719849,AP (train/test): 0.35679197311401367/0.3402269780635834

 10%|████████▎                                                                          | 6/60 [00:16<02:31,  2.81s/it]

Epoch [6/60], Loss (train/test): 0.6202696561813354/0.6147946119308472,AP (train/test): 0.3598787188529968/0.3395801782608032

 12%|█████████▋                                                                         | 7/60 [00:19<02:26,  2.77s/it]

Epoch [7/60], Loss (train/test): 0.5673589110374451/0.5613898038864136,AP (train/test): 0.35599344968795776/0.34036514163017273

 13%|███████████                                                                        | 8/60 [00:22<02:24,  2.79s/it]

Epoch [8/60], Loss (train/test): 0.5294434428215027/0.5244604349136353,AP (train/test): 0.3596964478492737/0.3416207730770111

 15%|████████████▍                                                                      | 9/60 [00:25<02:22,  2.80s/it]

Epoch [9/60], Loss (train/test): 0.4807590842247009/0.4765709340572357,AP (train/test): 0.3637484908103943/0.33894431591033936

 17%|█████████████▋                                                                    | 10/60 [00:28<02:20,  2.81s/it]

Epoch [10/60], Loss (train/test): 0.45043501257896423/0.4455312490463257,AP (train/test): 0.3675524890422821/0.34296831488609314

 18%|███████████████                                                                   | 11/60 [00:30<02:17,  2.81s/it]

Epoch [11/60], Loss (train/test): 0.41714951395988464/0.41257423162460327,AP (train/test): 0.3703007400035858/0.34266170859336853

 20%|████████████████▍                                                                 | 12/60 [00:33<02:12,  2.77s/it]

Epoch [12/60], Loss (train/test): 0.4105447232723236/0.409442275762558,AP (train/test): 0.37954896688461304/0.34543877840042114

 22%|█████████████████▊                                                                | 13/60 [00:36<02:10,  2.78s/it]

Epoch [13/60], Loss (train/test): 0.3629574477672577/0.3602370619773865,AP (train/test): 0.39314180612564087/0.34348464012145996

 23%|███████████████████▏                                                              | 14/60 [00:39<02:08,  2.79s/it]

Epoch [14/60], Loss (train/test): 0.33215412497520447/0.32975074648857117,AP (train/test): 0.40387246012687683/0.34521955251693726

 25%|████████████████████▌                                                             | 15/60 [00:41<02:05,  2.79s/it]

Epoch [15/60], Loss (train/test): 0.3062874972820282/0.3086121082305908,AP (train/test): 0.41986674070358276/0.3463272750377655

 27%|█████████████████████▊                                                            | 16/60 [00:44<02:02,  2.79s/it]

Epoch [16/60], Loss (train/test): 0.3436046838760376/0.3604962229728699,AP (train/test): 0.4438178539276123/0.3455957770347595

 28%|███████████████████████▏                                                          | 17/60 [00:47<01:58,  2.75s/it]

Epoch [17/60], Loss (train/test): 0.26136669516563416/0.2847442030906677,AP (train/test): 0.4691108465194702/0.3446581959724426

 30%|████████████████████████▌                                                         | 18/60 [00:50<01:55,  2.75s/it]

Epoch [18/60], Loss (train/test): 0.27203088998794556/0.31419074535369873,AP (train/test): 0.5063139200210571/0.3455232083797455

 32%|█████████████████████████▉                                                        | 19/60 [00:52<01:53,  2.78s/it]

Epoch [19/60], Loss (train/test): 0.22149747610092163/0.27435043454170227,AP (train/test): 0.5794321298599243/0.34171074628829956

 33%|███████████████████████████▎                                                      | 20/60 [00:55<01:50,  2.77s/it]

Epoch [20/60], Loss (train/test): 0.24403943121433258/0.32118692994117737,AP (train/test): 0.6232032179832458/0.3436119258403778

 35%|████████████████████████████▋                                                     | 21/60 [00:58<01:48,  2.78s/it]

Epoch [21/60], Loss (train/test): 0.1930728405714035/0.2931336462497711,AP (train/test): 0.6498362421989441/0.3451089560985565

 37%|██████████████████████████████                                                    | 22/60 [01:01<01:43,  2.73s/it]

Epoch [22/60], Loss (train/test): 0.16943281888961792/0.3042278289794922,AP (train/test): 0.7046636343002319/0.3439667224884033

 38%|███████████████████████████████▍                                                  | 23/60 [01:03<01:41,  2.75s/it]

Epoch [23/60], Loss (train/test): 0.15520282089710236/0.3032066226005554,AP (train/test): 0.752971887588501/0.3415341377258301

 40%|████████████████████████████████▊                                                 | 24/60 [01:06<01:39,  2.77s/it]

Epoch [24/60], Loss (train/test): 0.12835370004177094/0.2704026997089386,AP (train/test): 0.7605338096618652/0.3416764736175537

 42%|██████████████████████████████████▏                                               | 25/60 [01:09<01:36,  2.76s/it]

Epoch [25/60], Loss (train/test): 0.11063802242279053/0.27144983410835266,AP (train/test): 0.8119220733642578/0.33881068229675293

 43%|███████████████████████████████████▌                                              | 26/60 [01:12<01:34,  2.77s/it]

Epoch [26/60], Loss (train/test): 0.09751538932323456/0.27470770478248596,AP (train/test): 0.8651002645492554/0.3414894938468933

 45%|████████████████████████████████████▉                                             | 27/60 [01:14<01:29,  2.72s/it]

Epoch [27/60], Loss (train/test): 0.09587813913822174/0.30045297741889954,AP (train/test): 0.9004677534103394/0.34030255675315857

 47%|██████████████████████████████████████▎                                           | 28/60 [01:17<01:27,  2.74s/it]

Epoch [28/60], Loss (train/test): 0.17685531079769135/0.46411439776420593,AP (train/test): 0.7230708599090576/0.342303991317749

 48%|███████████████████████████████████████▋                                          | 29/60 [01:20<01:25,  2.75s/it]

Epoch [29/60], Loss (train/test): 0.08069266378879547/0.3196503221988678,AP (train/test): 0.9010448455810547/0.3417521119117737

 50%|█████████████████████████████████████████                                         | 30/60 [01:23<01:23,  2.77s/it]

Epoch [30/60], Loss (train/test): 0.07246159762144089/0.28572583198547363,AP (train/test): 0.8873960971832275/0.3411283493041992

 52%|██████████████████████████████████████████▎                                       | 31/60 [01:26<01:21,  2.81s/it]

Epoch [31/60], Loss (train/test): 0.12439132481813431/0.4451102018356323,AP (train/test): 0.8101372122764587/0.3404877185821533

 53%|███████████████████████████████████████████▋                                      | 32/60 [01:29<01:19,  2.83s/it]

Epoch [32/60], Loss (train/test): 0.08284441381692886/0.2779175043106079,AP (train/test): 0.8401228785514832/0.3384436368942261

 55%|█████████████████████████████████████████████                                     | 33/60 [01:31<01:16,  2.83s/it]

Epoch [33/60], Loss (train/test): 0.05904845520853996/0.30512791872024536,AP (train/test): 0.9392639994621277/0.3383660316467285

 55%|█████████████████████████████████████████████                                     | 33/60 [01:34<01:17,  2.86s/it]

Epoch [34/60], Loss (train/test): 0.05678825080394745/0.2951892912387848,AP (train/test): 0.9367544054985046/0.3383786082267761
Early stopping after epoch 33, model saved at epoch 23, validation loss 0.2704026997089386.
23 0.2704026997089386 0.12835370004177094 0.2704026997089386

C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
  0%|                                                                                           | 0/60 [00:00<?, ?it/s]C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
  2%|█▍                                                                                 | 1/60 [00:02<02:56,  2.99s/it]

Epoch [1/60], Loss (train/test): 0.9485416412353516/0.9446085095405579,AP (train/test): 0.3372068405151367/0.33862945437431335

  3%|██▊                                                                                | 2/60 [00:05<02:50,  2.93s/it]

Epoch [2/60], Loss (train/test): 0.7685393691062927/0.7593593001365662,AP (train/test): 0.33789074420928955/0.3362922668457031

  5%|████▏                                                                              | 3/60 [00:08<02:40,  2.82s/it]

Epoch [3/60], Loss (train/test): 0.680221438407898/0.6675960421562195,AP (train/test): 0.3460386395454407/0.34374499320983887

  7%|█████▌                                                                             | 4/60 [00:11<02:36,  2.79s/it]

Epoch [4/60], Loss (train/test): 0.5746671557426453/0.559669554233551,AP (train/test): 0.3591708838939667/0.3526543080806732

  8%|██████▉                                                                            | 5/60 [00:14<02:32,  2.77s/it]

Epoch [5/60], Loss (train/test): 0.5186446309089661/0.5029574632644653,AP (train/test): 0.36419016122817993/0.34833329916000366

 10%|████████▎                                                                          | 6/60 [00:16<02:29,  2.77s/it]

Epoch [6/60], Loss (train/test): 0.48341482877731323/0.4679335355758667,AP (train/test): 0.3683095872402191/0.3604751527309418

 12%|█████████▋                                                                         | 7/60 [00:19<02:24,  2.73s/it]

Epoch [7/60], Loss (train/test): 0.44380173087120056/0.42681238055229187,AP (train/test): 0.37145084142684937/0.35506388545036316

 13%|███████████                                                                        | 8/60 [00:22<02:22,  2.74s/it]

Epoch [8/60], Loss (train/test): 0.40885129570961/0.39079952239990234,AP (train/test): 0.37229305505752563/0.3552365005016327

 15%|████████████▍                                                                      | 9/60 [00:24<02:20,  2.75s/it]

Epoch [9/60], Loss (train/test): 0.38080841302871704/0.3636835813522339,AP (train/test): 0.38425952196121216/0.36159151792526245

 17%|█████████████▋                                                                    | 10/60 [00:27<02:17,  2.76s/it]

Epoch [10/60], Loss (train/test): 0.36949437856674194/0.3524734675884247,AP (train/test): 0.3856050670146942/0.3609367311000824

 18%|███████████████                                                                   | 11/60 [00:30<02:15,  2.76s/it]

Epoch [11/60], Loss (train/test): 0.349388062953949/0.33308055996894836,AP (train/test): 0.3936527967453003/0.3633696734905243

 20%|████████████████▍                                                                 | 12/60 [00:33<02:12,  2.76s/it]

Epoch [12/60], Loss (train/test): 0.32837972044944763/0.3118039667606354,AP (train/test): 0.40524324774742126/0.3617546260356903

 22%|█████████████████▊                                                                | 13/60 [00:36<02:09,  2.77s/it]

Epoch [13/60], Loss (train/test): 0.3126401901245117/0.3002777695655823,AP (train/test): 0.4269911050796509/0.36330997943878174

 23%|███████████████████▏                                                              | 14/60 [00:38<02:08,  2.79s/it]

Epoch [14/60], Loss (train/test): 0.3110111951828003/0.30600783228874207,AP (train/test): 0.44483065605163574/0.36477285623550415

 25%|████████████████████▌                                                             | 15/60 [00:41<02:04,  2.77s/it]

Epoch [15/60], Loss (train/test): 0.2858278155326843/0.29481932520866394,AP (train/test): 0.4760516881942749/0.3627278506755829

 27%|█████████████████████▊                                                            | 16/60 [00:44<02:02,  2.79s/it]

Epoch [16/60], Loss (train/test): 0.26384425163269043/0.2860416769981384,AP (train/test): 0.5305421948432922/0.3604359030723572

 28%|███████████████████████▏                                                          | 17/60 [00:47<01:59,  2.78s/it]

Epoch [17/60], Loss (train/test): 0.26790758967399597/0.3135867714881897,AP (train/test): 0.5721441507339478/0.35931703448295593

 30%|████████████████████████▌                                                         | 18/60 [00:50<01:57,  2.80s/it]

Epoch [18/60], Loss (train/test): 0.20720639824867249/0.2788899838924408,AP (train/test): 0.6407662630081177/0.3544151782989502

 32%|█████████████████████████▉                                                        | 19/60 [00:52<01:53,  2.77s/it]

Epoch [19/60], Loss (train/test): 0.18197239935398102/0.27267634868621826,AP (train/test): 0.6907362937927246/0.35309216380119324

 33%|███████████████████████████▎                                                      | 20/60 [00:55<01:52,  2.80s/it]

Epoch [20/60], Loss (train/test): 0.17568199336528778/0.31249773502349854,AP (train/test): 0.7706426382064819/0.3549004793167114

 35%|████████████████████████████▋                                                     | 21/60 [00:58<01:50,  2.82s/it]

Epoch [21/60], Loss (train/test): 0.13487021625041962/0.2662200927734375,AP (train/test): 0.8014746904373169/0.35207241773605347

 37%|██████████████████████████████                                                    | 22/60 [01:01<01:47,  2.83s/it]

Epoch [22/60], Loss (train/test): 0.11843737959861755/0.2644689977169037,AP (train/test): 0.842918872833252/0.35587549209594727

 38%|███████████████████████████████▍                                                  | 23/60 [01:04<01:42,  2.77s/it]

Epoch [23/60], Loss (train/test): 0.13636109232902527/0.36520683765411377,AP (train/test): 0.9299384951591492/0.34827014803886414

 40%|████████████████████████████████▊                                                 | 24/60 [01:06<01:40,  2.80s/it]

Epoch [24/60], Loss (train/test): 0.07910026609897614/0.26415926218032837,AP (train/test): 0.95392245054245/0.35057616233825684

 42%|██████████████████████████████████▏                                               | 25/60 [01:09<01:38,  2.80s/it]

Epoch [25/60], Loss (train/test): 0.06357648968696594/0.2738099694252014,AP (train/test): 0.9817230701446533/0.3456694781780243

 43%|███████████████████████████████████▌                                              | 26/60 [01:12<01:35,  2.80s/it]

Epoch [26/60], Loss (train/test): 0.05911032482981682/0.2678721249103546,AP (train/test): 0.9893956184387207/0.33934152126312256

 45%|████████████████████████████████████▉                                             | 27/60 [01:15<01:30,  2.75s/it]

Epoch [27/60], Loss (train/test): 0.04540032520890236/0.3120075762271881,AP (train/test): 0.9980704188346863/0.3442935347557068

 47%|██████████████████████████████████████▎                                           | 28/60 [01:17<01:28,  2.76s/it]

Epoch [28/60], Loss (train/test): 0.03490802273154259/0.2886523902416229,AP (train/test): 0.9990488886833191/0.34238359332084656

 48%|███████████████████████████████████████▋                                          | 29/60 [01:20<01:26,  2.78s/it]

Epoch [29/60], Loss (train/test): 0.027462774887681007/0.3021467328071594,AP (train/test): 0.9992121458053589/0.3435172736644745

 50%|█████████████████████████████████████████                                         | 30/60 [01:23<01:22,  2.75s/it]

Epoch [30/60], Loss (train/test): 0.023728614673018456/0.29504281282424927,AP (train/test): 0.9998066425323486/0.3444669246673584

 52%|██████████████████████████████████████████▎                                       | 31/60 [01:26<01:20,  2.76s/it]

Epoch [31/60], Loss (train/test): 0.02209712378680706/0.317985862493515,AP (train/test): 0.9997156858444214/0.3432183265686035

 53%|███████████████████████████████████████████▋                                      | 32/60 [01:28<01:17,  2.77s/it]

Epoch [32/60], Loss (train/test): 0.019395045936107635/0.3097192049026489,AP (train/test): 0.9998612403869629/0.3429715633392334

 55%|█████████████████████████████████████████████                                     | 33/60 [01:31<01:14,  2.77s/it]

Epoch [33/60], Loss (train/test): 0.017996931448578835/0.33537915349006653,AP (train/test): 0.9999880790710449/0.34425055980682373

 55%|█████████████████████████████████████████████                                     | 33/60 [01:34<01:17,  2.87s/it]

Epoch [34/60], Loss (train/test): 0.01440467033535242/0.3106585144996643,AP (train/test): 0.9997835159301758/0.34446606040000916
Early stopping after epoch 33, model saved at epoch 23, validation loss 0.26415926218032837.
23 0.26415926218032837 0.07910026609897614 0.26415926218032837

  0%|                                                                                           | 0/60 [00:00<?, ?it/s]C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
  2%|█▍                                                                                 | 1/60 [00:02<02:48,  2.85s/it]

Epoch [1/60], Loss (train/test): 1.0940879583358765/1.0948376655578613,AP (train/test): 0.33762115240097046/0.33525288105010986

  3%|██▊                                                                                | 2/60 [00:05<02:44,  2.84s/it]

Epoch [2/60], Loss (train/test): 0.9277344942092896/0.9244091510772705,AP (train/test): 0.34084272384643555/0.33853113651275635

  5%|████▏                                                                              | 3/60 [00:08<02:41,  2.82s/it]

Epoch [3/60], Loss (train/test): 0.7954733967781067/0.7890461683273315,AP (train/test): 0.34775465726852417/0.34294137358665466

  7%|█████▌                                                                             | 4/60 [00:11<02:34,  2.76s/it]

Epoch [4/60], Loss (train/test): 0.717531144618988/0.7109476923942566,AP (train/test): 0.35526299476623535/0.33919018507003784

  8%|██████▉                                                                            | 5/60 [00:13<02:32,  2.78s/it]

Epoch [5/60], Loss (train/test): 0.6508401036262512/0.6459912657737732,AP (train/test): 0.36240601539611816/0.33993667364120483

 10%|████████▎                                                                          | 6/60 [00:16<02:28,  2.74s/it]

Epoch [6/60], Loss (train/test): 0.5738461017608643/0.564173698425293,AP (train/test): 0.3688391447067261/0.3435541093349457

 12%|█████████▋                                                                         | 7/60 [00:19<02:26,  2.76s/it]

Epoch [7/60], Loss (train/test): 0.5117529034614563/0.5038157105445862,AP (train/test): 0.37083932757377625/0.3447468876838684

 13%|███████████                                                                        | 8/60 [00:22<02:25,  2.80s/it]

Epoch [8/60], Loss (train/test): 0.4560418426990509/0.44312790036201477,AP (train/test): 0.3710979223251343/0.34655851125717163

 15%|████████████▍                                                                      | 9/60 [00:25<02:22,  2.79s/it]

Epoch [9/60], Loss (train/test): 0.43721121549606323/0.4239433705806732,AP (train/test): 0.373691201210022/0.3488154113292694

 17%|█████████████▋                                                                    | 10/60 [00:27<02:17,  2.75s/it]

Epoch [10/60], Loss (train/test): 0.41063353419303894/0.39652174711227417,AP (train/test): 0.3838246464729309/0.3511456251144409

 18%|███████████████                                                                   | 11/60 [00:30<02:15,  2.77s/it]

Epoch [11/60], Loss (train/test): 0.38783934712409973/0.3766728937625885,AP (train/test): 0.3872978687286377/0.35323023796081543

 20%|████████████████▍                                                                 | 12/60 [00:33<02:13,  2.78s/it]

Epoch [12/60], Loss (train/test): 0.36706358194351196/0.35496971011161804,AP (train/test): 0.39603298902511597/0.35561996698379517

 22%|█████████████████▊                                                                | 13/60 [00:36<02:09,  2.75s/it]

Epoch [13/60], Loss (train/test): 0.3435302972793579/0.33330339193344116,AP (train/test): 0.4087696969509125/0.3558390140533447

 23%|███████████████████▏                                                              | 14/60 [00:38<02:08,  2.79s/it]

Epoch [14/60], Loss (train/test): 0.3241541087627411/0.318576842546463,AP (train/test): 0.41784748435020447/0.354396790266037

 25%|████████████████████▌                                                             | 15/60 [00:41<02:06,  2.81s/it]

Epoch [15/60], Loss (train/test): 0.3097635507583618/0.30980026721954346,AP (train/test): 0.44717860221862793/0.35509103536605835

 27%|█████████████████████▊                                                            | 16/60 [00:44<02:05,  2.84s/it]

Epoch [16/60], Loss (train/test): 0.29060932993888855/0.30151695013046265,AP (train/test): 0.46736130118370056/0.35282039642333984

 28%|███████████████████████▏                                                          | 17/60 [00:47<01:59,  2.77s/it]

Epoch [17/60], Loss (train/test): 0.2862842082977295/0.31389784812927246,AP (train/test): 0.5193946361541748/0.34559735655784607

 30%|████████████████████████▌                                                         | 18/60 [00:50<01:57,  2.79s/it]

Epoch [18/60], Loss (train/test): 0.2434164583683014/0.28267425298690796,AP (train/test): 0.58677738904953/0.3425407111644745

 32%|█████████████████████████▉                                                        | 19/60 [00:52<01:52,  2.75s/it]

Epoch [19/60], Loss (train/test): 0.21593345701694489/0.2765932083129883,AP (train/test): 0.6346749067306519/0.33886557817459106

 33%|███████████████████████████▎                                                      | 20/60 [00:55<01:49,  2.75s/it]

Epoch [20/60], Loss (train/test): 0.1968906968832016/0.2836100459098816,AP (train/test): 0.6770800352096558/0.34012743830680847

 35%|████████████████████████████▋                                                     | 21/60 [00:58<01:47,  2.75s/it]

Epoch [21/60], Loss (train/test): 0.1682177186012268/0.2751738429069519,AP (train/test): 0.7363712191581726/0.33926138281822205

 37%|██████████████████████████████                                                    | 22/60 [01:01<01:44,  2.75s/it]

Epoch [22/60], Loss (train/test): 0.1501254141330719/0.2903481721878052,AP (train/test): 0.7765301465988159/0.3378792405128479

 38%|███████████████████████████████▍                                                  | 23/60 [01:03<01:40,  2.71s/it]

Epoch [23/60], Loss (train/test): 0.1877470165491104/0.3633243143558502,AP (train/test): 0.8340770602226257/0.3350982069969177

 40%|████████████████████████████████▊                                                 | 24/60 [01:06<01:38,  2.74s/it]

Epoch [24/60], Loss (train/test): 0.14600883424282074/0.3451533019542694,AP (train/test): 0.8855342864990234/0.33497482538223267

 42%|██████████████████████████████████▏                                               | 25/60 [01:09<01:36,  2.76s/it]

Epoch [25/60], Loss (train/test): 0.11833396553993225/0.32847166061401367,AP (train/test): 0.9271044731140137/0.3352451026439667

 43%|███████████████████████████████████▌                                              | 26/60 [01:11<01:33,  2.74s/it]

Epoch [26/60], Loss (train/test): 0.08703745156526566/0.29779964685440063,AP (train/test): 0.9576765894889832/0.3324582278728485

 45%|████████████████████████████████████▉                                             | 27/60 [01:14<01:28,  2.69s/it]

Epoch [27/60], Loss (train/test): 0.06962122023105621/0.2900855243206024,AP (train/test): 0.9770833849906921/0.3377416133880615

 47%|██████████████████████████████████████▎                                           | 28/60 [01:17<01:27,  2.73s/it]

Epoch [28/60], Loss (train/test): 0.0598105862736702/0.2994258999824524,AP (train/test): 0.9916863441467285/0.3368019759654999

 48%|███████████████████████████████████████▋                                          | 29/60 [01:20<01:25,  2.76s/it]

Epoch [29/60], Loss (train/test): 0.04553430527448654/0.27812913060188293,AP (train/test): 0.9968132972717285/0.3364241123199463

 50%|█████████████████████████████████████████                                         | 30/60 [01:22<01:22,  2.75s/it]

Epoch [30/60], Loss (train/test): 0.040724076330661774/0.2911462187767029,AP (train/test): 0.998990535736084/0.33677494525909424

 50%|█████████████████████████████████████████                                         | 30/60 [01:25<01:25,  2.86s/it]

Epoch [31/60], Loss (train/test): 0.03178154677152634/0.3089902400970459,AP (train/test): 0.9994842410087585/0.33473384380340576
Early stopping after epoch 30, model saved at epoch 20, validation loss 0.2751738429069519.
20 0.2751738429069519 0.1682177186012268 0.2751738429069519

C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
  0%|                                                                                           | 0/60 [00:00<?, ?it/s]C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
  2%|█▍                                                                                 | 1/60 [00:02<02:47,  2.84s/it]

Epoch [1/60], Loss (train/test): 1.1615015268325806/1.1632132530212402,AP (train/test): 0.3367527723312378/0.3333083987236023

  3%|██▊                                                                                | 2/60 [00:05<02:45,  2.85s/it]

Epoch [2/60], Loss (train/test): 1.0763407945632935/1.0773009061813354,AP (train/test): 0.3393574655056/0.33428090810775757

  5%|████▏                                                                              | 3/60 [00:08<02:42,  2.84s/it]

Epoch [3/60], Loss (train/test): 0.9652907252311707/0.9619314670562744,AP (train/test): 0.3469510078430176/0.33461469411849976

  7%|█████▌                                                                             | 4/60 [00:11<02:36,  2.79s/it]

Epoch [4/60], Loss (train/test): 0.836143434047699/0.8309971690177917,AP (train/test): 0.3551422953605652/0.33969807624816895

  8%|██████▉                                                                            | 5/60 [00:14<02:36,  2.84s/it]

Epoch [5/60], Loss (train/test): 0.7320155501365662/0.7224386930465698,AP (train/test): 0.35263746976852417/0.33900272846221924

 10%|████████▎                                                                          | 6/60 [00:17<02:35,  2.88s/it]

Epoch [6/60], Loss (train/test): 0.680103063583374/0.670045018196106,AP (train/test): 0.3553447127342224/0.3389652371406555

 12%|█████████▋                                                                         | 7/60 [00:19<02:30,  2.84s/it]

Epoch [7/60], Loss (train/test): 0.6146451830863953/0.6005353927612305,AP (train/test): 0.3562781512737274/0.3411039710044861

 13%|███████████                                                                        | 8/60 [00:22<02:27,  2.84s/it]

Epoch [8/60], Loss (train/test): 0.5458868145942688/0.5295421481132507,AP (train/test): 0.35892224311828613/0.34047991037368774

 15%|████████████▍                                                                      | 9/60 [00:25<02:24,  2.83s/it]

Epoch [9/60], Loss (train/test): 0.48495548963546753/0.46843427419662476,AP (train/test): 0.36539703607559204/0.34405624866485596

 17%|█████████████▋                                                                    | 10/60 [00:28<02:18,  2.76s/it]

Epoch [10/60], Loss (train/test): 0.43713802099227905/0.42187488079071045,AP (train/test): 0.3716154992580414/0.3386223018169403

 18%|███████████████                                                                   | 11/60 [00:30<02:15,  2.76s/it]

Epoch [11/60], Loss (train/test): 0.4137544333934784/0.39826059341430664,AP (train/test): 0.3781867027282715/0.338887095451355

 20%|████████████████▍                                                                 | 12/60 [00:33<02:12,  2.76s/it]

Epoch [12/60], Loss (train/test): 0.38246476650238037/0.36357155442237854,AP (train/test): 0.3840958774089813/0.33920952677726746

 22%|█████████████████▊                                                                | 13/60 [00:36<02:07,  2.72s/it]

Epoch [13/60], Loss (train/test): 0.35993507504463196/0.3429226577281952,AP (train/test): 0.38542598485946655/0.3417576253414154

 23%|███████████████████▏                                                              | 14/60 [00:39<02:06,  2.74s/it]

Epoch [14/60], Loss (train/test): 0.3352639973163605/0.31697022914886475,AP (train/test): 0.39756685495376587/0.34253114461898804

 25%|████████████████████▌                                                             | 15/60 [00:41<02:04,  2.77s/it]

Epoch [15/60], Loss (train/test): 0.3261541724205017/0.3130339980125427,AP (train/test): 0.40644627809524536/0.3427659273147583

 27%|█████████████████████▊                                                            | 16/60 [00:44<02:02,  2.78s/it]

Epoch [16/60], Loss (train/test): 0.2843600809574127/0.2759821116924286,AP (train/test): 0.4412493109703064/0.345061719417572

 28%|███████████████████████▏                                                          | 17/60 [00:47<02:00,  2.81s/it]

Epoch [17/60], Loss (train/test): 0.28307271003723145/0.28503066301345825,AP (train/test): 0.45071619749069214/0.3457295298576355

 30%|████████████████████████▌                                                         | 18/60 [00:50<01:56,  2.78s/it]

Epoch [18/60], Loss (train/test): 0.2630239725112915/0.2802843451499939,AP (train/test): 0.496198832988739/0.3411799371242523

 32%|█████████████████████████▉                                                        | 19/60 [00:52<01:51,  2.72s/it]

Epoch [19/60], Loss (train/test): 0.23778316378593445/0.2745538055896759,AP (train/test): 0.5430363416671753/0.3438047766685486

 33%|███████████████████████████▎                                                      | 20/60 [00:55<01:49,  2.73s/it]

Epoch [20/60], Loss (train/test): 0.21066215634346008/0.2669576406478882,AP (train/test): 0.6050733923912048/0.34403401613235474

 35%|████████████████████████████▋                                                     | 21/60 [00:58<01:47,  2.76s/it]

Epoch [21/60], Loss (train/test): 0.17965425550937653/0.26137322187423706,AP (train/test): 0.64580899477005/0.3443262577056885

 37%|██████████████████████████████                                                    | 22/60 [01:01<01:44,  2.75s/it]

Epoch [22/60], Loss (train/test): 0.20251521468162537/0.3049994111061096,AP (train/test): 0.6488043069839478/0.34310755133628845

 38%|███████████████████████████████▍                                                  | 23/60 [01:04<01:42,  2.77s/it]

Epoch [23/60], Loss (train/test): 0.1443651169538498/0.2645130455493927,AP (train/test): 0.7013254165649414/0.3405081033706665

 40%|████████████████████████████████▊                                                 | 24/60 [01:06<01:39,  2.76s/it]

Epoch [24/60], Loss (train/test): 0.1523863673210144/0.2931969463825226,AP (train/test): 0.7021183371543884/0.3430759906768799

 42%|██████████████████████████████████▏                                               | 25/60 [01:09<01:37,  2.79s/it]

Epoch [25/60], Loss (train/test): 0.14254175126552582/0.30427637696266174,AP (train/test): 0.7589730024337769/0.3422510325908661

 43%|███████████████████████████████████▌                                              | 26/60 [01:12<01:34,  2.79s/it]

Epoch [26/60], Loss (train/test): 0.12994101643562317/0.3035159111022949,AP (train/test): 0.7966868281364441/0.3419620990753174

 45%|████████████████████████████████████▉                                             | 27/60 [01:15<01:32,  2.81s/it]

Epoch [27/60], Loss (train/test): 0.09712012112140656/0.26327645778656006,AP (train/test): 0.7954705953598022/0.3420480489730835

 47%|██████████████████████████████████████▎                                           | 28/60 [01:17<01:28,  2.77s/it]

Epoch [28/60], Loss (train/test): 0.09301900118589401/0.284977525472641,AP (train/test): 0.833443820476532/0.34263336658477783

 48%|███████████████████████████████████████▋                                          | 29/60 [01:20<01:26,  2.80s/it]

Epoch [29/60], Loss (train/test): 0.08785779774188995/0.2747619152069092,AP (train/test): 0.8290594816207886/0.3393974006175995

 50%|█████████████████████████████████████████                                         | 30/60 [01:23<01:22,  2.75s/it]

Epoch [30/60], Loss (train/test): 0.07494799047708511/0.2800823748111725,AP (train/test): 0.9004873037338257/0.33914703130722046

 50%|█████████████████████████████████████████                                         | 30/60 [01:26<01:26,  2.88s/it]

Epoch [31/60], Loss (train/test): 0.06653641909360886/0.2821054458618164,AP (train/test): 0.9342179298400879/0.3412705659866333
Early stopping after epoch 30, model saved at epoch 20, validation loss 0.26137322187423706.
20 0.26137322187423706 0.17965425550937653 0.26137322187423706

C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [40]:
# V6bs
import torch.nn.functional as F
from torch.nn import Linear, Conv1d, Embedding, AdaptiveMaxPool1d, AdaptiveAvgPool1d
from torch_geometric.nn import BatchNorm


class CNN1D(torch.nn.Module):
    def __init__(self,
                 conv_filters = 64,
                 conv_layers = 5,
                 emb_dim = 256,
                 kernel_size = 5,
                 linear_neurons=1024):

        super(CNN1D, self).__init__()
        
        self.emb_dim = emb_dim
        
        self.conv_filters = conv_filters

        self.num_conv1d_layers = conv_layers
        
        self.smile_emb = Embedding(num_embeddings=40, embedding_dim=emb_dim)

        self.conv1d_layers = nn.ModuleList()

        for i in range(conv_layers):
            if i == 0:
                self.conv1d_layers.append(
                    Conv1d(in_channels=emb_dim, out_channels=conv_filters * (i+1), kernel_size=kernel_size, stride=1))
            else:
                self.conv1d_layers.append(
                Conv1d(in_channels=conv_filters * i, out_channels=conv_filters * (i+1), kernel_size=kernel_size, stride=1))

        self.maxpool = AdaptiveMaxPool1d(1)
        self.avgpool = AdaptiveAvgPool1d(1)


        self.conv_act = nn.ReLU()
        self.batchnorm = nn.BatchNorm1d(11 + (conv_filters * (conv_layers) * 2))

        # self.actfc = nn.LeakyReLU(negative_slope=0.1)

        # self.gated_mlp = Gated_MLP_block(384)

        self.out_mlp = nn.Sequential(Linear(in_features= 11 + (conv_filters * (conv_layers) * 2), out_features=linear_neurons),
                                     nn.BatchNorm1d(linear_neurons),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                    Linear(in_features=linear_neurons, out_features=linear_neurons //2),
                                     nn.BatchNorm1d(linear_neurons // 2),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                     Linear(in_features=linear_neurons // 2, out_features=linear_neurons //4),
                                     nn.BatchNorm1d(linear_neurons // 4),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                     Linear(in_features=linear_neurons // 4, out_features=linear_neurons // 8),
                                     nn.BatchNorm1d(linear_neurons // 8),
                                     nn.LeakyReLU(),
                                     nn.Dropout(0.2),
                                     )

        self.layer_out = Linear(in_features=linear_neurons // 8, out_features=3)

    def forward(self, smile_vec,rdkit):

        smile_emb = self.smile_emb(smile_vec)

        conv_out = smile_emb.reshape(len(smile_emb), self.emb_dim, -1)

        for i in range(self.num_conv1d_layers):
            conv_out = self.conv1d_layers[i](conv_out)
            conv_out = self.conv_act(conv_out)

        conv_out_max = self.maxpool(conv_out).reshape(len(conv_out), self.conv_filters * self.num_conv1d_layers)
        conv_out_avg = self.avgpool(conv_out).reshape(len(conv_out), self.conv_filters * self.num_conv1d_layers)

        out = torch.cat((conv_out_max,conv_out_avg,rdkit), dim=1)
        out = self.batchnorm(out)

        out = self.out_mlp(out)

        out = self.layer_out(out)

        return out

In [19]:
def kappa_val_func(x,y_train_answers,pred_train_probas):
    x1,x2,x3 = x
    local_preds = pred_train_probas**np.array([x1,x2,x3])
    return -round(cohen_kappa_score(y_train_answers, local_preds.argmax(axis=1),weights='quadratic'),4)

In [20]:
indep_idx = []
with open(f'solubility_indep_ids.txt', 'r') as fp:
    for line in fp.read().splitlines():
        indep_idx.append(line)
ind_id = all_data[all_data.Id.isin(indep_idx)].index

In [23]:
val_ID = []
with open(f'solubility_valid_id_{0}.txt', 'r') as fp:
    for line in fp.read().splitlines():
        val_ID.append(line)

train_ID = []
with open(f'solubility_train_id_{0}.txt', 'r') as fp:
    for line in fp.read().splitlines():
        train_ID.append(line)

uni_id = val_ID+train_ID

train_idx = all_data[all_data.Id.isin(uni_id)].index

train_loader = get_loader(np.concatenate(all_data['enc_smiles'].loc[train_idx].to_numpy()).reshape(len(all_data['enc_smiles'].loc[train_idx]),-1),
                          descr_scaled[train_idx],
                          y=all_data[TARGET].loc[train_idx, TARGET].to_numpy(), 
                          with_y=True, 
                          shuffle=False, 
                          batch_size=BATCH_SIZE)

In [24]:

##V1 - BATCH_SIZE = int(2048) EPOCHS = 60 LR = 1e-4 WD = 0.00
## A version - BATCH_SIZE = int(2048) EPOCHS = 60 LR = 1e-3 WD = 0.00
TARGET = ['sol_category']
MODEL_VERSION = 'V6B_s2'
BATCH_SIZE = int(2048)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
WH_BALANCE = ''
all_pred_probas = []
for fold in range(0,5):

    curr_name = f"1DCNN_SOL_{fold}_{MODEL_VERSION}_{WH_BALANCE}"

    neural_folder = '1dCNN_pytorch_neurals_upd/'
    
    neural = CNN1D()
    neural.load_state_dict(torch.load(neural_folder+curr_name,map_location=device))
    neural = neural.to(device)
    neural.eval()

    
    sol_types = ['LOW','MEDIUM','HIGH']
    
    ##find coefs

    y_answers = []
    pred_probas = []
    with torch.no_grad():
        m = nn.Softmax(dim=1)
        for smile_emb,rdkit_f,y in train_loader:
            out = neural(smile_emb.to(device),rdkit_f.to(device))
            pred = m(out.to(torch.device("cpu"))).detach().numpy()
            y_answers.extend(y.to(torch.device("cpu")).detach().numpy())
            pred_probas.extend(pred)
    y_answers = np.array(y_answers)
    all_pred_probas.append(pred_probas)

In [25]:
from scipy.optimize import minimize
bounds = [(0.01,4)]*3
x0 = [1.0]*3
pred_probas = np.array(all_pred_probas).mean(axis=0)
minim_res = minimize(kappa_val_func, x0,args=(y_answers,pred_probas), method='powell',bounds=bounds)
coefs = np.array(minim_res.x)

with open(f'kappa_coefs_5_neurals_together_{curr_name}.txt', 'w') as fp:
    for item in coefs:
        # write each item on a new line
        fp.write("%s\n" % item)

In [31]:
all_indep_probas = []
for fold in range(0,5):
    pred_probas_indep = []
    y_answers = []
    curr_name = f"1DCNN_SOL_{fold}_{MODEL_VERSION}_{WH_BALANCE}"

    neural_folder = '1dCNN_pytorch_neurals_upd/'
    
    neural = CNN1D()
    neural.load_state_dict(torch.load(neural_folder+curr_name,map_location=device))
    neural = neural.to(device)
    neural.eval()

    
    sol_types = ['LOW','MEDIUM','HIGH']
    
    ##find coefs

    y_answers = []
    pred_probas = []
    with torch.no_grad():
        m = nn.Softmax(dim=1)
        for smile_emb,rdkit_f,y in indep_loader:
            out = neural(smile_emb.to(device),rdkit_f.to(device))
            pred = m(out.to(torch.device("cpu"))).detach().numpy()
            y_answers.extend(y.to(torch.device("cpu")).detach().numpy())
            pred_probas_indep.extend(pred)
            
    all_indep_probas.append(np.array(pred_probas_indep))

y_answers = np.array(y_answers)
pred_probas = np.array(all_indep_probas).mean(axis=0)

In [34]:
##indep
precs = []
recs = []
aps = []

for cl in range(0, 3):
    precision, recall, _ = precision_recall_curve((y_answers==cl).astype(int), pred_probas[:, cl], pos_label=1)
    average_precision = average_precision_score((y_answers==cl).astype(int), pred_probas[:, cl], pos_label=1)
    precs.append(precision)
    recs.append(recall)
    aps.append(average_precision)

print(classification_report(y_answers, pred_probas.argmax(axis=1), target_names=sol_types),
      file=open(neural_folder+'5_split_indep_classification_report'+curr_name+'.txt', 'a'))
print(classification_report(y_answers, (pred_probas**coefs).argmax(axis=1), target_names=sol_types),
      file=open(neural_folder+'5_split_coef_indep_classification_report'+curr_name+'.txt', 'a'))


mpl.rcParams['figure.dpi'] = 150
kappa = round(cohen_kappa_score(y_answers, pred_probas.argmax(axis=1),weights='quadratic'),4)
adj_kappa = round(cohen_kappa_score(y_answers, (pred_probas**coefs).argmax(axis=1),weights='quadratic'),4)
plt.title(f'Precision-recall curve, Quadratic kappa {kappa}, adjusted {adj_kappa}', fontsize=14)

for marker in range(3):
    plt.plot(recs[marker], precs[marker], label=f'AUC {sol_types[marker]} = %0.2f' % aps[marker])
plt.legend(loc='lower right')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.xticks(np.arange(0, 1.1, 0.1), fontsize=9)
plt.yticks(np.arange(0, 1.1, 0.1), fontsize=9)
plt.grid(True)
plt.savefig(neural_folder+f'indep_precision_recall_5_split_{curr_name}.png', format="png")
plt.close()

C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alexey\miniconda3\envs\work_env\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [39]:
test_data = pd.read_csv('test.csv')

In [44]:

# all_data['smiles'] = all_data['smiles'].apply(normalize_smile)
# all_data['enc_smiles'] = all_data['smiles'].apply(encode_smile)
test_descr = []
# calc some descriptors
for m in tqdm(test_data.smiles):
    test_descr.append([Descriptors.MolLogP(Chem.MolFromSmiles(m)),
                  Descriptors.TPSA(Chem.MolFromSmiles(m)),
                  Descriptors.NHOHCount(Chem.MolFromSmiles(m)),
                  Descriptors.NOCount(Chem.MolFromSmiles(m)),
                  Descriptors.NumHAcceptors(Chem.MolFromSmiles(m)),
                  Descriptors.NumHDonors(Chem.MolFromSmiles(m)),
                  Descriptors.NumRotatableBonds(Chem.MolFromSmiles(m)),
                  Descriptors.NumHeteroatoms(Chem.MolFromSmiles(m)),
                  Descriptors.FractionCSP3(Chem.MolFromSmiles(m)),
                  Descriptors.ExactMolWt(Chem.MolFromSmiles(m)),
                  rdMolDescriptors.CalcNumAromaticRings(Chem.MolFromSmiles(m))])

test_descr = np.asarray(test_descr)
scaler_descr = torch.load('rdkit_descriptor_scaler_sol')
test_descr_scaled = scaler_descr.transform(test_descr)

100%|███████████████████████████████████████████████████████████████████████████| 30307/30307 [01:13<00:00, 414.07it/s]

In [45]:
test_data['norm_smiles'] = test_data['smiles'].apply(normalize_smile)
test_data['enc_smiles'] = test_data['norm_smiles'].apply(encode_smile)

In [46]:
test_loader = get_loader(np.concatenate(test_data['enc_smiles'].to_numpy()).reshape(len(test_data['enc_smiles']),-1),
                          test_descr_scaled,
                          with_y=False, 
                          shuffle=False, 
                          batch_size=BATCH_SIZE)

In [50]:
coefs = []

with open(f'kappa_coefs_5_neurals_together_{curr_name}.txt', 'r') as fp:
    for line in fp.read().splitlines():
        coefs.append(float(line))

coefs = np.array(coefs)

In [48]:

##V1 - BATCH_SIZE = int(2048) EPOCHS = 60 LR = 1e-4 WD = 0.00
## A version - BATCH_SIZE = int(2048) EPOCHS = 60 LR = 1e-3 WD = 0.00
TARGET = ['sol_category']
MODEL_VERSION = 'V6B_s2'
BATCH_SIZE = int(2048)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
WH_BALANCE = ''
all_pred_probas = []
for fold in range(0,5):

    curr_name = f"1DCNN_SOL_{fold}_{MODEL_VERSION}_{WH_BALANCE}"

    neural_folder = '1dCNN_pytorch_neurals_upd/'
    
    neural = CNN1D()
    neural.load_state_dict(torch.load(neural_folder+curr_name,map_location=device))
    neural = neural.to(device)
    neural.eval()

    
    sol_types = ['LOW','MEDIUM','HIGH']
    
    ##find coefs

    y_answers = []
    pred_probas = []
    with torch.no_grad():
        m = nn.Softmax(dim=1)
        for smile_emb,rdkit_f in test_loader:
            out = neural(smile_emb.to(device),rdkit_f.to(device))
            pred = m(out.to(torch.device("cpu"))).detach().numpy()
            pred_probas.extend(pred)
    all_pred_probas.append(pred_probas)

In [53]:
test_pred_probas = np.array(all_pred_probas).mean(axis=0)
answers = (test_pred_probas**coefs).argmax(axis=1)

In [54]:
template = pd.read_csv('submission_template_rdm.csv')
template['Id'] = test_data['Id']
template['pred'] = answers
template.set_index('Id',inplace=True,drop=True)
template.to_csv('kaggle_1dCNN_5_split_coef.csv')